environments:
  flags:
    pipelines:
      - continuous
    agents:
      - aa040791-db48-4221-b64e-ab9f0baffdbc 
pipelines:
  continuous:
    group: flags
    materials:
      source:
        scm: 5e9b10ad-3832-46fa-b040-a5cd9d596ffb
        destination: .
        blacklist:
          - master
    stages:
      - linting:
          jobs:
            linting:
              tasks:
               - exec:
                   command: tox
                   arguments:
                     - "-e linting"
            security:
              tasks:
                - exec:
                   command: tox
                   arguments:
                     - "-e security"
      - unit:
          jobs:
            tests_pypy3:
              environment_variables:
                COVERAGE_FILE: .coverage.unit.pypy3
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.unit.pypy3
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e pypy3-cov"
                      - "--"
                      - "-m unit"
                      - "--junitxml=report.xml"
            tests_py36:
              environment_variables:
                COVERAGE_FILE: .coverage.unit.py36
              artifacts:
                - test:
                    source: report.xml
                - build:
                    source: .coverage.unit.py36
                    destination: coveragedata/
              tasks:
                - exec:
                    run_if: passed
                    command: tox
                    arguments:
                      - "-e py36-cov"
                      - "--"
                      - "-m unit"
                      - "--junitxml=report.xml"
 
