properties([
	pipelineTriggers([pollSCM('')])
])

node() {
	stage('linting') {
		echo "Running linting"
	}

	stage('security') {
		echo "Running security"
	}

	stage('unit tests') {
		echo "Running unit tests without coverage"
	}
}
